name: Build documentations

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: DEBIAN_FRONTEND=noninteractive \
        sudo install -y g++ libicu-dev pkg-config
    - run: python -m pip install --no-cache-dir .
    - run: python -m pip install --no-cache-dir -r docs/requirements.txt
    - run: sphinx-build -b html docs public
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: public/
