name: Build documentations

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: sudo apt install -y g++ libicu-dev pkg-config
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install python packages
      run: |
        python -m pip install --no-cache-dir .
        python -m pip install --no-cache-dir -r docs/requirements.txt

    - name: Build docs
      run: sphinx-build -b html docs public

    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: public/
